% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Math448: Chapter 4 HW},
  pdfauthor={Zahraa Alshalal},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Math448: Chapter 4 HW}
\author{Zahraa Alshalal}
\date{2023-04-03}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.0     v readr     2.1.4
## v forcats   1.0.0     v stringr   1.5.0
## v ggplot2   3.4.1     v tibble    3.2.0
## v lubridate 1.9.2     v tidyr     1.3.0
## v purrr     1.0.1     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ISLR2)}
\FunctionTok{library}\NormalTok{(ISLR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'ISLR'
## 
## The following objects are masked from 'package:ISLR2':
## 
##     Auto, Credit
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(MASS)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'MASS'
## 
## The following object is masked from 'package:ISLR2':
## 
##     Boston
## 
## The following object is masked from 'package:dplyr':
## 
##     select
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(class)}
\FunctionTok{library}\NormalTok{(e1071)}
\end{Highlighting}
\end{Shaded}

\hypertarget{conceptual-questions}{%
\subsection{Conceptual Questions}\label{conceptual-questions}}

\hypertarget{exercise-3}{%
\subsubsection{Exercise 3:}\label{exercise-3}}

\begin{itemize}
\item
  The Bayes classifier is not linear: quadratic \[\begin{aligned}
   p_k(x)=\frac{\pi_k\frac{1}{\sqrt{2\pi\sigma_k}}exp(-\frac{1}{2\sigma^2_k})(x-\mu_l)^2)}{\sum\pi_l\frac{1}{\sqrt{2\pi\sigma}}exp(-\frac{1}{2\sigma^2_l})(x-\mu_l)^2)}\\   
   \log{(p_k(x))}=\frac{\log{(\pi_k)}+\log{(\frac{1}{\sqrt{2\pi\sigma_k}}})+-\frac{1}{\sigma^2_k}(x-\mu_k)^2}{\log(\sum\pi_l\frac{1}{\sqrt{2\pi\sigma}}exp(-\frac{1}{2\sigma^2_l})(x-\mu_l)^2))}\\
   \log{(p_k(x))\log(\sum\pi_l\frac{1}{\sqrt{2\pi\sigma}}exp(-\frac{1}{2\sigma^2_l})(x-\mu_l)^2))=\log(\pi_k)+\log{(\frac{1}{\sqrt{2\pi\sigma_k}}})+-\frac{1}{\sigma^2_k}(x-\mu_k)^2}\\
   \delta(x)=\log(\pi_k)+\log{(\frac{1}{\sqrt{2\pi\sigma_k}}})+-\frac{1}{2\sigma^2_k}(x-\mu_k)^2\\
  \end{aligned}\]
\item
  \(\delta(x)\) in the final term, the discriminant is not linear.
\end{itemize}

\hypertarget{exercise-6}{%
\subsubsection{Exercise 6:}\label{exercise-6}}

\begin{itemize}
\item
  \begin{enumerate}
  \def\labelenumi{\alph{enumi})}
  \tightlist
  \item
  \end{enumerate}
\end{itemize}

\[
\begin{aligned}
P(X) &= \frac{\exp(\hat\beta_0 + \hat\beta_1X_1 + \hat\beta_2X_2)}{1 + \exp(\hat\beta_0 + \hat\beta_1X_1 + \hat\beta_2X_2)}\\
P(X) &= \frac{\exp(-0.5)}{1+\exp(-0.5)} = 0.38 
\end{aligned}
\]

\begin{itemize}
\item
  \begin{enumerate}
  \def\labelenumi{\alph{enumi})}
  \setcounter{enumi}{1}
  \tightlist
  \item
  \end{enumerate}
\end{itemize}

\[
\begin{aligned}
\log(\frac{P(X)}{1 - P(X)}) &= \hat\beta_0 + \hat\beta_1X_1 + \hat\beta_2X_2\\
\log(\frac{0.5}{1 - 0.5}) &= -6 + 0.05X1 + 3.5\\
X_1 &= 50 hours. 
\end{aligned}
\]

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{applied-questions}{%
\subsection{Applied Questions:}\label{applied-questions}}

\hypertarget{exercise-13}{%
\subsubsection{Exercise 13:}\label{exercise-13}}

\hypertarget{a}{%
\paragraph{a)}\label{a}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(Weekly)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Year           Lag1               Lag2               Lag3         
##  Min.   :1990   Min.   :-18.1950   Min.   :-18.1950   Min.   :-18.1950  
##  1st Qu.:1995   1st Qu.: -1.1540   1st Qu.: -1.1540   1st Qu.: -1.1580  
##  Median :2000   Median :  0.2410   Median :  0.2410   Median :  0.2410  
##  Mean   :2000   Mean   :  0.1506   Mean   :  0.1511   Mean   :  0.1472  
##  3rd Qu.:2005   3rd Qu.:  1.4050   3rd Qu.:  1.4090   3rd Qu.:  1.4090  
##  Max.   :2010   Max.   : 12.0260   Max.   : 12.0260   Max.   : 12.0260  
##       Lag4               Lag5              Volume            Today         
##  Min.   :-18.1950   Min.   :-18.1950   Min.   :0.08747   Min.   :-18.1950  
##  1st Qu.: -1.1580   1st Qu.: -1.1660   1st Qu.:0.33202   1st Qu.: -1.1540  
##  Median :  0.2380   Median :  0.2340   Median :1.00268   Median :  0.2410  
##  Mean   :  0.1458   Mean   :  0.1399   Mean   :1.57462   Mean   :  0.1499  
##  3rd Qu.:  1.4090   3rd Qu.:  1.4050   3rd Qu.:2.05373   3rd Qu.:  1.4050  
##  Max.   : 12.0260   Max.   : 12.0260   Max.   :9.32821   Max.   : 12.0260  
##  Direction 
##  Down:484  
##  Up  :605  
##            
##            
##            
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatterplot matrix.}
\FunctionTok{pairs}\NormalTok{(Weekly)}
\end{Highlighting}
\end{Shaded}

\includegraphics{math448HW-3ZahraaAlshalal_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Correlation matrix.}
\FunctionTok{cor}\NormalTok{(Weekly[, }\SpecialCharTok{{-}}\DecValTok{9}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Year         Lag1        Lag2        Lag3         Lag4
## Year    1.00000000 -0.032289274 -0.03339001 -0.03000649 -0.031127923
## Lag1   -0.03228927  1.000000000 -0.07485305  0.05863568 -0.071273876
## Lag2   -0.03339001 -0.074853051  1.00000000 -0.07572091  0.058381535
## Lag3   -0.03000649  0.058635682 -0.07572091  1.00000000 -0.075395865
## Lag4   -0.03112792 -0.071273876  0.05838153 -0.07539587  1.000000000
## Lag5   -0.03051910 -0.008183096 -0.07249948  0.06065717 -0.075675027
## Volume  0.84194162 -0.064951313 -0.08551314 -0.06928771 -0.061074617
## Today  -0.03245989 -0.075031842  0.05916672 -0.07124364 -0.007825873
##                Lag5      Volume        Today
## Year   -0.030519101  0.84194162 -0.032459894
## Lag1   -0.008183096 -0.06495131 -0.075031842
## Lag2   -0.072499482 -0.08551314  0.059166717
## Lag3    0.060657175 -0.06928771 -0.071243639
## Lag4   -0.075675027 -0.06107462 -0.007825873
## Lag5    1.000000000 -0.05851741  0.011012698
## Volume -0.058517414  1.00000000 -0.033077783
## Today   0.011012698 -0.03307778  1.000000000
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The correlations between the ``lag'' variables and today's returns are
  close to zero. There is correlation is between ``Year'' and
  ``Volume''. No other patterns are discernible.\\
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(Weekly)}
\FunctionTok{plot}\NormalTok{(Volume)}
\end{Highlighting}
\end{Shaded}

\includegraphics{math448HW-3ZahraaAlshalal_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{itemize}
\tightlist
\item
  The ``Volume'' plot shows that it is increasing over time.
\end{itemize}

\hypertarget{b}{%
\paragraph{b)}\label{b}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.glm }\OtherTok{=} \FunctionTok{glm}\NormalTok{(Direction }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Lag1 }\SpecialCharTok{+}\NormalTok{ Lag2 }\SpecialCharTok{+}\NormalTok{ Lag3 }\SpecialCharTok{+}\NormalTok{ Lag4 }\SpecialCharTok{+}\NormalTok{ Lag5 }\SpecialCharTok{+}\NormalTok{ Volume, }\AttributeTok{data =}\NormalTok{ Weekly, }\AttributeTok{family =}\NormalTok{ binomial)}
\FunctionTok{summary}\NormalTok{(fit.glm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + 
##     Volume, family = binomial, data = Weekly)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6949  -1.2565   0.9913   1.0849   1.4579  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)   
## (Intercept)  0.26686    0.08593   3.106   0.0019 **
## Lag1        -0.04127    0.02641  -1.563   0.1181   
## Lag2         0.05844    0.02686   2.175   0.0296 * 
## Lag3        -0.01606    0.02666  -0.602   0.5469   
## Lag4        -0.02779    0.02646  -1.050   0.2937   
## Lag5        -0.01447    0.02638  -0.549   0.5833   
## Volume      -0.02274    0.03690  -0.616   0.5377   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1496.2  on 1088  degrees of freedom
## Residual deviance: 1486.4  on 1082  degrees of freedom
## AIC: 1500.4
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Lag 2 appears to have some statistical significance with a p-value is
  less than 0.05.
\end{itemize}

\hypertarget{c}{%
\paragraph{c)}\label{c}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probs }\OtherTok{=} \FunctionTok{predict}\NormalTok{(fit.glm, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred.glm }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\StringTok{"Down"}\NormalTok{, }\FunctionTok{length}\NormalTok{(probs))}
\NormalTok{pred.glm[probs }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{] }\OtherTok{=} \StringTok{"Up"}
\FunctionTok{table}\NormalTok{(pred.glm, Direction)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Direction
## pred.glm Down  Up
##     Down   54  48
##     Up    430 557
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#the percentage of correct predictions on the training data}
\NormalTok{correct\_predictions }\OtherTok{=}\NormalTok{ (}\DecValTok{54}\SpecialCharTok{+}\DecValTok{557}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{54}\SpecialCharTok{+}\DecValTok{557}\SpecialCharTok{+}\DecValTok{48}\SpecialCharTok{+}\DecValTok{430}\NormalTok{)}
\NormalTok{correct\_predictions}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5610652
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{error\_predictions }\OtherTok{=} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ correct\_predictions}
\NormalTok{error\_predictions}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4389348
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{market\_up }\OtherTok{=}\NormalTok{ (}\DecValTok{557}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{557}\SpecialCharTok{+}\DecValTok{48}\NormalTok{)}
\NormalTok{market\_up}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9206612
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{market\_down }\OtherTok{=} \DecValTok{54}\SpecialCharTok{/}\NormalTok{(}\DecValTok{54}\SpecialCharTok{+}\DecValTok{430}\NormalTok{)}
\NormalTok{market\_down}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1115702
\end{verbatim}

\begin{itemize}
\tightlist
\item
  We may conclude that the percentage of correct predictions on the
  training data is 56.11\%. The training error rate 43.89\%. For the
  weeks when the market goes up, the model is right 92.07\% of the time.
  For weeks when the market goes down, the model is right only 11.16\%.
\end{itemize}

\hypertarget{d}{%
\paragraph{d)}\label{d}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train }\OtherTok{=}\NormalTok{ (Year }\SpecialCharTok{\textless{}} \DecValTok{2009}\NormalTok{)}
\NormalTok{Weekly}\FloatTok{.910} \OtherTok{=}\NormalTok{ Weekly[}\SpecialCharTok{!}\NormalTok{train, ]}
\NormalTok{Direction}\FloatTok{.910} \OtherTok{=}\NormalTok{ Direction[}\SpecialCharTok{!}\NormalTok{train]}
\NormalTok{fit.glm2 }\OtherTok{=} \FunctionTok{glm}\NormalTok{(Direction }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Lag2, }\AttributeTok{data =}\NormalTok{ Weekly, }\AttributeTok{family =}\NormalTok{ binomial, }\AttributeTok{subset =}\NormalTok{ train)}
\FunctionTok{summary}\NormalTok{(fit.glm2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Direction ~ Lag2, family = binomial, data = Weekly, 
##     subset = train)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.536  -1.264   1.021   1.091   1.368  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)   
## (Intercept)  0.20326    0.06428   3.162  0.00157 **
## Lag2         0.05810    0.02870   2.024  0.04298 * 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1354.7  on 984  degrees of freedom
## Residual deviance: 1350.5  on 983  degrees of freedom
## AIC: 1354.5
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probs2 }\OtherTok{=} \FunctionTok{predict}\NormalTok{(fit.glm2, Weekly}\FloatTok{.910}\NormalTok{, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred.glm2 }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\StringTok{"Down"}\NormalTok{, }\FunctionTok{length}\NormalTok{(probs2))}
\NormalTok{pred.glm2[probs2 }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"Up"}
\FunctionTok{table}\NormalTok{(pred.glm2, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Direction.910
## pred.glm2 Down Up
##      Down    9  5
##      Up     34 56
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#the percentage of correct predictions on the training data}
\NormalTok{correct\_predictions1 }\OtherTok{=}\NormalTok{ (}\DecValTok{9}\SpecialCharTok{+}\DecValTok{56}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{104}\NormalTok{)}
\NormalTok{correct\_predictions1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.625
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{error\_predictions1 }\OtherTok{=} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ correct\_predictions1}
\NormalTok{error\_predictions1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.375
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{market\_up1 }\OtherTok{=}\NormalTok{ (}\DecValTok{56}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{56}\SpecialCharTok{+}\DecValTok{5}\NormalTok{)}
\NormalTok{market\_up1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9180328
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{market\_down1 }\OtherTok{=} \DecValTok{9}\SpecialCharTok{/}\NormalTok{(}\DecValTok{9}\SpecialCharTok{+}\DecValTok{34}\NormalTok{)}
\NormalTok{market\_down1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2093023
\end{verbatim}

\begin{itemize}
\tightlist
\item
  In this case, the percentage of correct predictions on the test data
  is 62.5\%. the test error rate is 37.5\%. For the weeks when the
  market goes up, the model is right 91.80\% of the time. For the weeks
  when the market goes down, the model is right only 20.93\% of the
  time.
\end{itemize}

\hypertarget{e}{%
\paragraph{e)}\label{e}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lda.fit }\OtherTok{=} \FunctionTok{lda}\NormalTok{(Direction }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Lag2, }\AttributeTok{data =}\NormalTok{ Weekly, }\AttributeTok{subset =}\NormalTok{ train)}
\NormalTok{lda.fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## lda(Direction ~ Lag2, data = Weekly, subset = train)
## 
## Prior probabilities of groups:
##      Down        Up 
## 0.4477157 0.5522843 
## 
## Group means:
##             Lag2
## Down -0.03568254
## Up    0.26036581
## 
## Coefficients of linear discriminants:
##            LD1
## Lag2 0.4414162
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lda.pred }\OtherTok{=} \FunctionTok{predict}\NormalTok{(lda.fit, Weekly}\FloatTok{.910}\NormalTok{)}
\FunctionTok{table}\NormalTok{(lda.pred}\SpecialCharTok{$}\NormalTok{class, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Direction.910
##        Down Up
##   Down    9  5
##   Up     34 56
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(lda.pred}\SpecialCharTok{$}\NormalTok{class }\SpecialCharTok{==}\NormalTok{ Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.625
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The percentage of correct predictions on the test data is 62.5\%.
\end{itemize}

\hypertarget{f}{%
\paragraph{f)}\label{f}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qda.fit }\OtherTok{=} \FunctionTok{qda}\NormalTok{(Direction }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Lag2, }\AttributeTok{data =}\NormalTok{ Weekly, }\AttributeTok{subset =}\NormalTok{ train)}
\NormalTok{qda.fit }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## qda(Direction ~ Lag2, data = Weekly, subset = train)
## 
## Prior probabilities of groups:
##      Down        Up 
## 0.4477157 0.5522843 
## 
## Group means:
##             Lag2
## Down -0.03568254
## Up    0.26036581
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.qda }\OtherTok{=} \FunctionTok{predict}\NormalTok{(qda.fit, Weekly}\FloatTok{.910}\NormalTok{)}\SpecialCharTok{$}\NormalTok{class}
\FunctionTok{table}\NormalTok{(pred.qda, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Direction.910
## pred.qda Down Up
##     Down    0  0
##     Up     43 61
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(pred.qda }\SpecialCharTok{==}\NormalTok{ Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5865385
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The percentage of correct predictions on the test data is 58.7\%.
\end{itemize}

\hypertarget{g}{%
\paragraph{g)}\label{g}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train.X }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(Lag2[train])}
\NormalTok{test.X }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(Lag2[}\SpecialCharTok{!}\NormalTok{train])}
\NormalTok{train.Direction }\OtherTok{=}\NormalTok{ Direction[train]}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{knn.pred }\OtherTok{=} \FunctionTok{knn}\NormalTok{(train.X, test.X, train.Direction, }\AttributeTok{k =} \DecValTok{1}\NormalTok{)}
\FunctionTok{table}\NormalTok{(knn.pred, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Direction.910
## knn.pred Down Up
##     Down   21 30
##     Up     22 31
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(knn.pred }\SpecialCharTok{==}\NormalTok{ Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The percentage of correct predictions on the test data is 50\%.
\end{itemize}

\hypertarget{h}{%
\paragraph{h)}\label{h}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bayes.fit}\OtherTok{=}\FunctionTok{naiveBayes}\NormalTok{(Direction}\SpecialCharTok{\textasciitilde{}}\NormalTok{Lag2 ,}\AttributeTok{data=}\NormalTok{Weekly ,}\AttributeTok{subset=}\NormalTok{train)}
\NormalTok{bayes.fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Naive Bayes Classifier for Discrete Predictors
## 
## Call:
## naiveBayes.default(x = X, y = Y, laplace = laplace)
## 
## A-priori probabilities:
## Y
##      Down        Up 
## 0.4477157 0.5522843 
## 
## Conditional probabilities:
##       Lag2
## Y             [,1]     [,2]
##   Down -0.03568254 2.199504
##   Up    0.26036581 2.317485
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bayes.pre }\OtherTok{=} \FunctionTok{predict}\NormalTok{(bayes.fit, Weekly}\FloatTok{.910}\NormalTok{)}
\FunctionTok{table}\NormalTok{(bayes.pre, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Direction.910
## bayes.pre Down Up
##      Down    0  0
##      Up     43 61
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{correct\_predictions1 }\OtherTok{=}\NormalTok{ (}\DecValTok{61}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{104}\NormalTok{)}
\NormalTok{correct\_predictions1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5865385
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The percentage of correct predictions on the test data is 58.65\%\%.
\end{itemize}

\hypertarget{i}{%
\paragraph{i)}\label{i}}

\begin{verbatim}
The regression model percentage of correct predictions is 62.5% of the time which is the highest between all the models. The regression method appears to provide the best results.      
\end{verbatim}

\hypertarget{j}{%
\paragraph{j)}\label{j}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Logistic regression with Lag2:Lag1}
\NormalTok{glm.fit }\OtherTok{=} \FunctionTok{glm}\NormalTok{(Direction }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Lag2}\SpecialCharTok{:}\NormalTok{Lag1, }\AttributeTok{data =}\NormalTok{ Weekly, }\AttributeTok{family =}\NormalTok{ binomial, }\AttributeTok{subset =}\NormalTok{ train)}
\NormalTok{glm.probs }\OtherTok{=} \FunctionTok{predict}\NormalTok{(glm.fit, Weekly}\FloatTok{.910}\NormalTok{, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{glm.pred }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\StringTok{"Down"}\NormalTok{, }\FunctionTok{length}\NormalTok{(glm.probs))}
\NormalTok{glm.pred[glm.probs }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{] }\OtherTok{=} \StringTok{"Up"}
\NormalTok{Direction}\FloatTok{.0910} \OtherTok{=}\NormalTok{ Direction[}\SpecialCharTok{!}\NormalTok{train]}
\FunctionTok{table}\NormalTok{(glm.pred, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Direction.910
## glm.pred Down Up
##     Down    1  1
##     Up     42 60
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(glm.pred }\SpecialCharTok{==}\NormalTok{ Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5865385
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# LDA with Lag2 interaction with Lag1}
\NormalTok{lda.fit }\OtherTok{=} \FunctionTok{lda}\NormalTok{(Direction }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Lag2}\SpecialCharTok{:}\NormalTok{Lag1, }\AttributeTok{data =}\NormalTok{ Weekly, }\AttributeTok{subset =}\NormalTok{ train)}
\NormalTok{lda.pred }\OtherTok{=} \FunctionTok{predict}\NormalTok{(lda.fit, Weekly}\FloatTok{.910}\NormalTok{)}
\FunctionTok{mean}\NormalTok{(lda.pred}\SpecialCharTok{$}\NormalTok{class }\SpecialCharTok{==}\NormalTok{ Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5769231
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# QDA with sqrt(abs(Lag2))}
\NormalTok{qda.fit }\OtherTok{=} \FunctionTok{qda}\NormalTok{(Direction }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Lag2 }\SpecialCharTok{+} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{abs}\NormalTok{(Lag2)), }\AttributeTok{data =}\NormalTok{ Weekly, }\AttributeTok{subset =}\NormalTok{ train)}
\NormalTok{qda.class }\OtherTok{=} \FunctionTok{predict}\NormalTok{(qda.fit, Weekly}\FloatTok{.910}\NormalTok{)}\SpecialCharTok{$}\NormalTok{class}
\FunctionTok{table}\NormalTok{(qda.class, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Direction.910
## qda.class Down Up
##      Down   12 13
##      Up     31 48
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(qda.class }\SpecialCharTok{==}\NormalTok{ Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5769231
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# KNN k =10}
\NormalTok{knn.pred }\OtherTok{=} \FunctionTok{knn}\NormalTok{(train.X, test.X, train.Direction, }\AttributeTok{k =} \DecValTok{10}\NormalTok{)}
\FunctionTok{table}\NormalTok{(knn.pred, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Direction.910
## knn.pred Down Up
##     Down   17 18
##     Up     26 43
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(knn.pred }\SpecialCharTok{==}\NormalTok{ Direction}\FloatTok{.0910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5769231
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# KNN k = 100}
\NormalTok{knn.pred }\OtherTok{=} \FunctionTok{knn}\NormalTok{(train.X, test.X, train.Direction, }\AttributeTok{k =} \DecValTok{100}\NormalTok{)}
\FunctionTok{table}\NormalTok{(knn.pred, Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Direction.910
## knn.pred Down Up
##     Down    9 12
##     Up     34 49
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(knn.pred }\SpecialCharTok{==}\NormalTok{ Direction}\FloatTok{.910}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5576923
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Out of these combinations, the original logistic regression and LDA
  have the best performance in terms of test error rates.
\end{itemize}

\hypertarget{exercise-15}{%
\subsubsection{Exercise 15:}\label{exercise-15}}

\hypertarget{a-1}{%
\paragraph{a)}\label{a-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Power }\OtherTok{=} \ControlFlowTok{function}\NormalTok{() \{}
    \DecValTok{2}\SpecialCharTok{\^{}}\DecValTok{3}
\NormalTok{\}}
\FunctionTok{print}\NormalTok{(}\FunctionTok{Power}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8
\end{verbatim}

\hypertarget{b-1}{%
\paragraph{b)}\label{b-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Power2 }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(x, a) \{}
\NormalTok{    x}\SpecialCharTok{\^{}}\NormalTok{a}
\NormalTok{\}}
\FunctionTok{Power2}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6561
\end{verbatim}

\hypertarget{c-1}{%
\paragraph{c)}\label{c-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Power2}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Power2}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DecValTok{17}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.2518e+15
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Power2}\NormalTok{(}\DecValTok{131}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2248091
\end{verbatim}

\hypertarget{d-1}{%
\paragraph{d)}\label{d-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Power3 }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(x, a) \{}
\NormalTok{    result }\OtherTok{=}\NormalTok{ x}\SpecialCharTok{\^{}}\NormalTok{a}
    \FunctionTok{return}\NormalTok{(result)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{e-1}{%
\paragraph{e)}\label{e-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}
\FunctionTok{plot}\NormalTok{(x, }\FunctionTok{Power3}\NormalTok{(x, }\DecValTok{2}\NormalTok{), }\AttributeTok{log =} \StringTok{"xy"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Log of y = x\^{}2"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Log of x"}\NormalTok{, }
    \AttributeTok{main =} \StringTok{"Log of x\^{}2 versus Log of x"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{math448HW-3ZahraaAlshalal_files/figure-latex/unnamed-chunk-34-1.pdf}

\hypertarget{f-1}{%
\paragraph{f)}\label{f-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PlotPower }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(x, a) \{}
    \FunctionTok{plot}\NormalTok{(x, }\FunctionTok{Power3}\NormalTok{(x, a))}
\NormalTok{\}}
\FunctionTok{PlotPower}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{math448HW-3ZahraaAlshalal_files/figure-latex/unnamed-chunk-35-1.pdf}

\end{document}
